### PR TITLE
ADDED QUACKS

### PR DESCRIPTION
**Pull request by ykris45**
New Token

### CODE REVIEW

**Comment by Luivatra** [comment]
Please update according to the changes in the main branch

**Comment by ykris45** [comment]
@Luivatra resolved

**Comment by Luivatra** [comment]
quacks is not an nft

**Comment by ykris45** [comment]
> quacks is not an nft

Yess quacks is not NFT but its a token powerde by duckpools.io https://ergexplorer.com/token#089990451bb430f05a85f4ef3bcb6ebf852b3d6ee68d86d78658b9ccef20074f

**Pull request closed without merging**
